-- Sistem Rebutan Spot Foto Database Schema
-- Run this script in your Supabase SQL Editor

-- 1. Create spots table
CREATE TABLE IF NOT EXISTS public.spots (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 1,
    chosen_by TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create kelas table
CREATE TABLE IF NOT EXISTS public.kelas (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    spot_id INTEGER REFERENCES public.spots(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create settings table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create bookings table (New system for reliable atomic bookings)
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spot_id INT REFERENCES public.spots(id) NOT NULL,
    kelas_id INT REFERENCES public.kelas(id) NOT NULL,
    kelas_name TEXT NOT NULL,
    user_name TEXT NOT NULL,
    user_email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    UNIQUE(kelas_id) -- Ensures a class can only book one spot
);

-- 5. Create the Atomic RPC Function (Mencegah Race Condition)
CREATE OR REPLACE FUNCTION book_spot_atomic(
  p_spot_id INT, 
  p_kelas_id INT, 
  p_kelas_name TEXT, 
  p_user_name TEXT,
  p_user_email TEXT
) RETURNS jsonb AS $$
DECLARE
  v_spot public.spots%ROWTYPE;
  v_kelas public.kelas%ROWTYPE;
  v_booking_count INT;
  v_formatted_string TEXT;
BEGIN
  -- Lock the specific spot row to prevent concurrent updates
  SELECT * INTO v_spot FROM public.spots WHERE id = p_spot_id FOR UPDATE;
  
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Spot tidak ditemukan');
  END IF;

  -- Lock the kelas row
  SELECT * INTO v_kelas FROM public.kelas WHERE id = p_kelas_id FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Kelas tidak ditemukan');
  END IF;

  -- Check if kelas already has a spot_id
  IF v_kelas.spot_id IS NOT NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Kelas sudah memilih spot');
  END IF;

  -- Check if spot capacity is reached
  SELECT COUNT(*) INTO v_booking_count FROM public.bookings WHERE spot_id = p_spot_id;
  
  IF v_booking_count >= v_spot.capacity THEN
    RETURN jsonb_build_object('success', false, 'error', 'Spot sudah penuh');
  END IF;

  -- Insert into bookings table
  INSERT INTO public.bookings (spot_id, kelas_id, kelas_name, user_name, user_email)
  VALUES (p_spot_id, p_kelas_id, p_kelas_name, p_user_name, p_user_email);

  -- Update kelas table
  UPDATE public.kelas SET spot_id = p_spot_id WHERE id = p_kelas_id;

  -- Format the string for UI
  v_formatted_string := p_kelas_name || ' (oleh: ' || p_user_name || ')';

  -- Update spots table chosen_by array (for UI compatibility)
  UPDATE public.spots 
  SET chosen_by = array_append(chosen_by, v_formatted_string)
  WHERE id = p_spot_id;

  RETURN jsonb_build_object('success', true, 'message', 'Booking berhasil!');
EXCEPTION
  WHEN unique_violation THEN
    RETURN jsonb_build_object('success', false, 'error', 'Kelas sudah memilih spot (Conflict)');
  WHEN OTHERS THEN
    RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$ LANGUAGE plpgsql;

-- 6. Grant Permissions
GRANT EXECUTE ON FUNCTION book_spot_atomic(INT, INT, TEXT, TEXT, TEXT) TO authenticated, anon;

-- Setup RLS
ALTER TABLE public.spots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kelas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all public.spots" ON public.spots FOR ALL USING (true);
CREATE POLICY "Allow all public.kelas" ON public.kelas FOR ALL USING (true);
CREATE POLICY "Allow all public.settings" ON public.settings FOR ALL USING (true);
CREATE POLICY "Allow all public.bookings" ON public.bookings FOR ALL USING (true);

-- Allow realtime for the required tables
alter publication supabase_realtime add table public.spots, public.kelas, public.settings;

-- 7. Insert Initial Data
INSERT INTO public.settings (key, value) VALUES ('booking_start_time', '2025-01-01T00:00:00.000Z') ON CONFLICT DO NOTHING;

INSERT INTO public.spots (name, capacity, chosen_by) VALUES
    ('Pocin', 3, '{}'),
    ('Panggung Pocin', 3, '{}'),
    ('Depan Pos Satpam arah gedung A', 3, '{}'),
    ('Perpustakaan', 3, '{}'),
    ('Lapangan Dekat Dapur Guru', 3, '{}'),
    ('Pohon samping Greenhouse', 3, '{}'),
    ('Visi Misi', 3, '{}'),
    ('Gazebo Rooftop Gedung D', 3, '{}'),
    ('Pintu Gedung A', 3, '{}'),
    ('Tangga gedung A', 3, '{}'),
    ('Bawah Jembatan Ros', 3, '{}'),
    ('Kursi Benedict room', 3, '{}'),
    ('Panggung Benedict room', 3, '{}')
ON CONFLICT DO NOTHING;

INSERT INTO public.kelas (name, spot_id) VALUES
    ('X-A', NULL), ('X-B', NULL), ('X-C', NULL), ('X-D', NULL), ('X-E', NULL),
    ('X-F', NULL), ('X-G', NULL), ('X-H', NULL), ('X-I', NULL), ('X-J', NULL),
    ('X-K', NULL), ('X-L', NULL), ('X-M', NULL),
    ('XI-A1', NULL), ('XI-A2', NULL), ('XI-A3', NULL),
    ('XI-B1', NULL), ('XI-B2', NULL),
    ('XI-C1', NULL), ('XI-C2', NULL), ('XI-C3', NULL),
    ('XI-D1', NULL), ('XI-E1', NULL), ('XI-E2', NULL), ('XI-F1', NULL),
    ('XII-A1', NULL), ('XII-A2', NULL), ('XII-A3', NULL), ('XII-A4', NULL), ('XII-A5', NULL),
    ('XII-B1', NULL), ('XII-B2', NULL),
    ('XII-C1', NULL), ('XII-C2', NULL),
    ('XII-D1', NULL), ('XII-D2', NULL),
    ('XII-E1', NULL), ('XII-F1', NULL)
ON CONFLICT (name) DO NOTHING;
